import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from 'next/font/google'
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const glacialIndifferenceRegular = localFont({
  src: "./fonts/GlacialIndifference-Regular.otf",
  variable: "--font-glacial-indifference",
  weight: "400",
});

const glacialIndifferenceBold = localFont({
  src: "./fonts/GlacialIndifference-Bold.otf",
  variable: "--font-glacial-indifference-bold",
  weight: "700",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${glacialIndifferenceRegular.variable} ${glacialIndifferenceBold.variable} antialiased`}>
        <Header />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
